version: '1.0'
name: crontab
displayName: crontab
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
  schedule:
    - cron: '* 10 5 */10 * ? *'
variables:
  usr_path: gitee.com/scoop-installer/scoop.git
  global:
    - access_token
    - python_url
    - user_email
    - user_name
    - usr_login_name
stages:
  - name: stage-1c6a3f46
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor:
      - glsnames
    steps:
      - step: build@python
        name: build_python
        displayName: 镜像执行
        pythonVersion: '3.9'
        commands:
          - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - '# python 版本'
          - python --version
          - '# 设置git信息'
          - git config --global user.name ${user_name}
          - git config --global user.email ${user_email}
          - '# 设置依赖'
          - pip install OrderedDict pathlib pyyaml requests
          - '# 拉取脚本'
          - wget -O scoop-install.py ${python_url}
          - '# 执行脚本'
          - python scoop-install.py  'https://'${usr_login_name}':'${access_token}'@'${usr_path}
          - ''
        caches: []
        notify: []
        strategy:
          retry: '1'
          timeout: 3
strategy:
  blocking: false
